# Generated by Django 2.1.7 on 2019-05-14 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bcrsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrowInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bcrsystem.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='storageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='storageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='storageinfo',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bcrsystem.storageType'),
        ),
    ]
