# Generated by Django 2.1.7 on 2019-05-14 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bcrsystem', '0002_auto_20190514_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='clean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_clean', models.BooleanField(default=False)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bcrsystem.classroom')),
                ('cleaner_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_num', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='creditRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_decrease', models.BooleanField(default=False)),
                ('balance', models.IntegerField(default=0)),
                ('credit_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='borrowinfo',
            name='requirement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='storageinfo',
            name='storage_comment',
            field=models.TextField(null=True),
        ),
    ]
