# Generated by Django 2.1.7 on 2019-05-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='userInfo',
        ),
    ]
